version: '3'
volumes:
  frontend:
    driver: local
    driver_opts:
      device: /Users/transcendence/data/frontend
      type: volume
      o: bind

networks:
  transcendence-network:

services:
  frontend:
    build:
      context: ./docker/
      dockerfile: ../frontend/typescript-react-app/Dockerfile-frontend
    ports:
      - 3001:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - transcendence-network
    restart: on-failure